baseURL = "https://gallery.eleuther.ai/"
languageCode = "en-us"
title = "EleutherAI Gallery"
theme = "eai-theme"
contentDir = "content-gallery"
publishDir="public-gallery"
[params]
    logo="EleutherAI"
    logo_image_url="images/eai_logo.png"
    contact_mail="contact@eleuther.ai"
    site_type="gallery"
[menu]
  [[menu.main]]
    name = "Home"
    url = "https://eleuther.ai/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "https://eleuther.ai/about/"
    weight = 2
  [[menu.main]]
    name = "FAQ"
    url = "https://eleuther.ai/faq/"
    weight = 3
  [[menu.main]]
    name = "Blog"
    url = "https://blog.eleuther.ai"
    weight = 4
  [[menu.main]]
    name = "Publications"
    url = "https://eleuther.ai/publications/"
    weight = 5
  [[menu.main]]
    name = "Gallery"
    url = "/"
    weight = 6
  [[menu.main]]
    name = "Get Involved"
    url = "https://eleuther.ai/get-involved/"
    weight = 7